language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false

matrix:
  include:
  - node_js: node
    script:
    - yarn install
    - yarn build
    - danger run --verbose
  - node_js: '6'

